### PR TITLE
Add more known sedbots to plugins/re

### PR DESCRIPTION
**Pull request by Lonami**

### CODE REVIEW

**Comment by Lonami** [comment]
I think this will fail if there are deleted accounts in normal groups.

**Comment by Streetwalrus** [comment]
pls to fix

**Comment by Lonami** [comment]
@Streetwalrus who even uses normal groups now anyway. Channels return existing bots so clients can offer suggestions to commands when getting the full channel. Normal groups return all users. So deleted accounts can only exist in normal groups, which are pretty much not in use.

**Comment by Streetwalrus** [comment]
>who even uses normal groups now anyway

I do :<

**Pull request merged**
